// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emubzqneessxuunnwvpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVtdWJ6cW5lZXNzeHV1bm53dnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTQ3MzcsImV4cCI6MjA2OTA5MDczN30.3IDfaKQi8AmDcJBaqM5hDx7hNO2moJqKism13h-kS8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});